import fetch from "node-fetch";
import fetchToCurl from "fetch-to-curl";
import { logger, parseCsvFile, SQS, TesabizUtils } from "@meru/utils";
import { prisma } from "@meru/db";
import {
  PaymentMethod,
  TransactionStatus,
  TransactionType,
} from "@prisma/client";

export interface InfoTx {
  /** Pre-assigned system code */
  sisOrigen: string;
  /** Account alias number (mandatory for ReadQR) */
  codCuenta?: string;
}

export interface QRCobro {
  /** Unique transaction identifier generated by the POS */
  idTrans: string;
  /** Currency code: BOB / USD */
  codMoneda: string;
  /** Amount in cents without thousand separators or decimals */
  importe: number | string;
  /** Payment description */
  glosa: string;
  /** Expiration date in yyyy-MM-dd format (optional) */
  fechaVencimiento?: string;
  /** Indicates if the QR is for single-use (default: true) */
  usoUnico?: boolean;
  /** Operation code assigned to the process (optional) */
  codOperacion?: string;
  /** Mapping code associated with the account number */
  cuentaAbono: string;
  /** POS or terminal code where the QR is generated */
  pos: string;
  /** System user connected to the POS */
  cajero: string;
  /** QR generation channel: WEB / Mobile */
  canal: string;
  /** QR duration time in minutes (optional) */
  tiempoDuracion?: number;
  /** Product code defined by the merchant (optional) */
  codProducto?: string;
  /** Product category code defined by the merchant (optional) */
  catProducto?: string;
  /** Company branch generating the QR (optional) */
  sucursal?: string;
  /** Additional information defined by the merchant (optional) */
  info?: string;
}

export interface GenerateQRRequest {
  infoTx: InfoTx;
  qrCobro: QRCobro;
  codigoLectura?: string;
}

export interface GenerateQRResponse {
  header: { codReturn: string; txtReturn: string };
  hash?: string;
  idQr: string;
  idQrInterno: number;
}

export interface SecureResponse {
  payload:
  | GenerateQRResponse
  | ConsultQRResponse
  | ReadQRResponse
  | PayQRResponse;
  protectedHeader: {
    x5t: string;
    alg: string;
  };
}

export interface ConsultQRRequest {
  infoTx: InfoTx;
  qrTx: { idQr: string };
}

export interface Payment {
  idTxPagoEif: string;
  idTxPagoQR: string;
  codMoneda: string;
  importe: number;
  fechaPago: string;
  estado: string;
  codEifOrigen: string;
  ciNitOrigen: string;
  titularOrigen: string;
}

export interface ConsultQRResponse {
  header: { codReturn: string; txtReturn: string };
  qrTx: {
    idTrans: string;
    idQrInterno: number;
    idQr: string;
    codMoneda: string;
    importe: number;
    glosa: string;
    fechaVencimiento: string;
    usoUnico: boolean;
    cuentaAbono?: string;
    estado: string;
    pos?: string;
    cajero?: string;
    canal: string;
    sisOrigen: string;
    pagos: Array<Payment>;
  };
}

export interface SecureConsultQRResponse {
  payload: string;
  codReturn: string;
  txtReturn: string;
}

export interface BlockQRRequest {
  infoTx: InfoTx;
  qrTx: { idQr: string };
}

export interface BlockQRResponse {
  header: { codReturn: string; txtReturn: string };
}

export interface PayWithCardRequest {
  infoTx: InfoTx;
  tarjetaCobro: {
    idTrans: string;
    codMoneda: string;
    importe: number;
    glosa: string;
    pos: string;
    cajero: string;
    canal: string;
    codOperacion?: string;
    codProducto?: string;
    catProducto?: string;
    nroTarjeta: string;
    nombreTarjetaHabiente: string;
    fechaExpiracion: string;
    cvv2: string;
  };
}

export interface PayWithCardResponse {
  header: { codReturn: string; txtReturn: string };
  codigoAutorizacion?: string;
  idQr?: string;
  idPagoInterno?: number;
  status?: string;
}

export interface ModifyBranchRequest {
  infoTx: InfoTx & { user: string };
  qrTx: { idQr: string; sucursal: string; info: string };
}

export interface ModifyBranchResponse {
  header: { codReturn: string; txtReturn: string };
}

export interface ReadQRRequest {
  infoTx: InfoTx;
  infoQR: { hashQR: string };
}

export interface ReadQRResponse {
  header: { codReturn: string; txtReturn: string };
  qrCobro: {
    idQR: string;
    codMoneda: string;
    importe: number;
    glosa: string;
    codEIF: string;
    cuentaDestino: string;
    titularDestino: string;
    ciDestinatario?: string;
    fechaVencimiento: string;
    usoUnico: boolean;
  };
  codigoLectura?: string;
}

export interface PayQRRequest {
  infoTx: InfoTx & {
    canal: string;
    ip: string;
    codigoPais: string;
    zonaHoraria: string;
    latitud: string;
    longitud: string;
  };
  infoOrigen: {
    codEIF?: string;
    codCuenta: string;
    origenFondos: string;
    destinoFondos: string;
  };
  infoQR: {
    idQR: string;
    codMoneda: string;
    importe: number;
    glosa: string;
    codigoLectura?: string;
    codTransComercio?: string;
  };
}

export interface PayQRResponse {
  header: { codReturn: string; txtReturn: string };
  infoTx: {
    idTransEIF: string;
    idTransQRC: string;
    estadoTx: string;
  };
  codigoReturn?: string;
}

export interface ConsultQRByTransactionIdRequest {
  header: { codReturn: string; txtReturn: string };
  infoTx: {
    idTransEIF: string;
    idTransQRC: string;
    estadoTx: string;
  };
}

export interface AccountStatementRequest {
  infoAccount: {
    sisOrigen: string;
    codCuenta: string;
  };
  infoRpt: {
    fechaInicio: string; // yyyyMMddHHmmss
    fechaFin: string;    // yyyyMMddHHmmss
  };
}

export interface AccountStatementEntry {
  idTransEIF: string;
  debito: number;
  credito: number;
  moneda: string;
  glosa?: string;
  cuentaOrigen: string;
  cuentaDestino: string;
  eifOrigen: string;
  eifOrigenDesc?: string;
  eifDestino: string;
  eifDestinoDesc?: string;
  ciOrigen?: string;
  titularOrigen: string;
  ciDestino?: string;
  titularDestino?: string;
  detEstado?: string;
  estado: string;
  fechaPago?: string;
  tipo?: string;
}

export interface AccountStatementResponse {
  header: { codReturn: string; txtReturn: string };
  data: AccountStatementEntry[];
}

const CODE_COMERCIO = "MERU";
const TESABIZ_WITHDRAW_RECONCILIATION_MAX_ROWS = 200;

type TesabizWithdrawCsvRow = {
  transactionId?: string;
  transaction_id?: string;
  id?: string;
};

type ReconciliationDetail = {
  transactionId: string;
  action: string;
  tesabizStatus?: string;
  reason?: string;
};

type ReconciliationResult = {
  totalRows: number;
  completedInMeru: number;
  pendingInMeru: number;
  rejectedAndRefundQueuedInMeru: number;
  skippedNotFound: number;
  skippedNotWithdrawal: number;
  skippedNotTesabizWithdrawal: number;
  failed: number;
  details: ReconciliationDetail[];
};

class TesabizService {
  public static SIS_ORIGEN: string = "SO_Meru";
  public static CANAL: string = "WEB";
  public static CUENTA_ABONO: string = "CUENTA1_BOB";
  public static PAY_CANAL: string = "BILL";

  private static stagingBaseUrl: string = "https://testing.tesabiz.com";
  // private static baseUrl: string = "https://qrc.qr-pagos.com";
  private static baseUrl: string = "https://qrc.quicly.com.bo"; // Cambio solicitado por tesabiz problema DNS

  private static async request<T>(endpoint: string, data: any): Promise<T> {
    const url = `${this.baseUrl}${endpoint}`;
    const requestOptions = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    };

    const curl = fetchToCurl(url, requestOptions);

    const response = await fetch(url, requestOptions).then(async (res) => {
      if (!res.ok) {
        const error = await res.json();
        throw new Error(`HTTP error! Status: ${res.status}, ${error}`);
      }

      return res.json();
    });

    return response;
  }

  static async generateQR(
    data: GenerateQRRequest
  ): Promise<GenerateQRResponse> {
    return this.request("/ws-qr-service/qr/simple/encript64", data);
  }

  static async generateQRSecure(
    data: GenerateQRRequest
  ): Promise<GenerateQRResponse> {
    const payloadSigned = await TesabizUtils.sign({
      ...data,
    });

    const response: { txtReturn: string; payload: string } = await this.request(
      "/tesabiz-ws-security/sc/jws/encript64",
      {
        payload: payloadSigned,
        code: CODE_COMERCIO,
      }
    );

    if (response.txtReturn !== "SUCCESS" && response.txtReturn !== "EXITO") {
      logger.error(`[Tesabiz] generateQRSecure response: ${JSON.stringify(response)}`);
      throw new Error(`Failed to generate QR: ${response}`);
    }

    const decodedResponse: SecureResponse = (await TesabizUtils.decodeJws(
      response.payload
    )) as SecureResponse;

    return decodedResponse.payload as GenerateQRResponse;
  }

  static async consultQRSecure(
    data: ConsultQRRequest
  ): Promise<ConsultQRResponse> {
    const payloadSigned = await TesabizUtils.sign({
      ...data,
    });

    const response: SecureConsultQRResponse = (await this.request(
      "/tesabiz-ws-security/sc/jws/details",
      {
        payload: payloadSigned,
        code: CODE_COMERCIO,
      }
    )) as SecureConsultQRResponse;

    console.log(response);

    if (response.txtReturn !== "SUCCESS" && response.txtReturn !== "EXITO") {
      throw new Error(`Failed to generate QR: ${response.txtReturn}`);
    }

    const decodedResponse: SecureResponse = (await TesabizUtils.decodeJws(
      response.payload
    )) as SecureResponse;

    return decodedResponse.payload as ConsultQRResponse;
  }

  static async consultQRSecureByTransactionId(
    transactionId: string,
    qrCodePaymentId: string
  ): Promise<ConsultQRByTransactionIdRequest> {
    const payloadSigned = await TesabizUtils.sign({
      infoTx: {
        sisOrigen: TesabizService.SIS_ORIGEN
      },
      infoQR: {
        idQR: qrCodePaymentId,
        codTransComercio: transactionId
      }
    });

    const response: ConsultQRByTransactionIdRequest = (await this.request(
      "/tesabiz-ws-security/sc/jws/statusPayQr",
      {
        payload: payloadSigned,
        code: CODE_COMERCIO,
      }
    )) as ConsultQRByTransactionIdRequest;

    return response;
  }

  static async getPaymentDetails(tesabizId: string): Promise<Payment | null> {
    const paymentDetails: ConsultQRResponse = await this.consultQRSecure({
      infoTx: {
        sisOrigen: TesabizService.SIS_ORIGEN,
      },
      qrTx: {
        idQr: tesabizId,
      },
    });

    if (!paymentDetails.qrTx) {
      return null;
    }

    if (paymentDetails.qrTx.pagos.length === 0) {
      return null;
    }

    return paymentDetails.qrTx.pagos[0];
  }

  static async getPaymentDetailsByTransactionId({ qrCodePaymentId, transactionId }: {
    qrCodePaymentId: string,
    transactionId: string
  }): Promise<ConsultQRByTransactionIdRequest | null> {
    return this.consultQRSecureByTransactionId(transactionId, qrCodePaymentId);
  }

  static async consultAccountStatement(
    startDate: Date,
    endDate: Date
  ): Promise<AccountStatementEntry[]> {
    const pad = (n: number) => String(n).padStart(2, "0");
    const format = (d: Date) =>
      `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;

    const data: AccountStatementRequest = {
      infoAccount: {
        sisOrigen: TesabizService.SIS_ORIGEN,
        codCuenta: TesabizService.CUENTA_ABONO,
      },
      infoRpt: {
        fechaInicio: format(startDate),
        fechaFin: format(endDate),
      },
    };

    logger.info("[Tesabiz] consultAccountStatement", {
      fechaInicio: data.infoRpt.fechaInicio,
      fechaFin: data.infoRpt.fechaFin,
    });

    const response = await TesabizService.request<AccountStatementResponse>(
      "/ws-qr/qr/simple/accountStatement",
      data
    );

    // codReturn "0" = success for accountStatement endpoint (other endpoints use "EXITO")
    if (String(response.header.codReturn) !== "0") {
      throw new Error(
        `[Tesabiz] consultAccountStatement failed: ${response.header.txtReturn}`
      );
    }

    logger.info("[Tesabiz] consultAccountStatement result", {
      count: (response.data ?? []).length,
    });

    return response.data ?? [];
  }

  static async blockQR(data: BlockQRRequest): Promise<BlockQRResponse> {
    return this.request("/ws-qr-service/qr/simple/bloqued", data);
  }

  static async payWithCard(
    data: PayWithCardRequest
  ): Promise<PayWithCardResponse> {
    return this.request("/ws-card-payment/cp/card/payment", data);
  }

  static async modifyBranch(
    data: ModifyBranchRequest
  ): Promise<ModifyBranchResponse> {
    return this.request("/ws-qr-service/qr/simple/updateSucursal", data);
  }

  static async readQR(data: ReadQRRequest): Promise<ReadQRResponse> {
    return this.request("/ws-qr/qr/simple/readQR", data);
  }

  static async payQR(data: PayQRRequest): Promise<PayQRResponse> {
    return this.request("/ws-qr/qr/simple/payQR", data);
  }

  static async readQRSecure(data: ReadQRRequest): Promise<ReadQRResponse> {
    logger.info(`[Tesabiz] readQRSecure data before send: ${JSON.stringify(data)}`);
    const payloadSigned = await TesabizUtils.sign({
      ...data,
    });

    const body = {
      payload: payloadSigned,
      code: CODE_COMERCIO,
    };

    const response: { txtReturn: string; payload: string } = await this.request(
      "/tesabiz-ws-security/sc/jws/readQR",
      body
    );

    if (response.txtReturn !== "SUCCESS" && response.txtReturn !== "EXITO") {
      throw new Error(`Failed to read QR: ${response.txtReturn}`);
    }

    const decodedResponse: SecureResponse = (await TesabizUtils.decodeJws(
      response.payload
    )) as SecureResponse;

    return decodedResponse.payload as ReadQRResponse;
  }

  static async payQRSecure(data: PayQRRequest): Promise<PayQRResponse> {
    logger.info(`[Tesabiz] payQRSecure data before send: ${JSON.stringify(data)}`);
    const payloadSigned = await TesabizUtils.sign({
      ...data,
    });

    const body = {
      payload: payloadSigned,
      code: CODE_COMERCIO,
    };

    const response: { txtReturn: string; payload: string, codReturn: string } = await this.request(
      "/tesabiz-ws-security/sc/jws/payQR",
      body
    );

    if (response.txtReturn !== "SUCCESS" && response.txtReturn !== "EXITO") {
      if (response.txtReturn.includes("Error al consumir el servicio")) {
        return {
          header: {
            codReturn: response.codReturn,
            txtReturn: response.txtReturn,
          },
          infoTx: {
            estadoTx: "ERROR",
          },
        } as PayQRResponse;
      } else {
        throw new Error(`Failed to pay QR: ${response.txtReturn}`);
      }
    }

    const decodedResponse: SecureResponse = (await TesabizUtils.decodeJws(
      response.payload
    )) as SecureResponse;

    return decodedResponse.payload as PayQRResponse;
  }

  private static normalizeTesabizWithdrawStatus(
    rawStatus?: string
  ): "completed" | "pending" | "rejected" | "unknown" {
    const normalized = (rawStatus ?? "").toString().trim().toUpperCase();

    if (!normalized) {
      return "unknown";
    }

    if (normalized === "PAGADO" || normalized.includes("COMPLET")) {
      return "completed";
    }

    // Rejected/cancelled statuses from Tesabiz map to rejected in Meru + refund.
    if (
      normalized.includes("RECHAZ") ||
      normalized.includes("CANCEL")
    ) {
      return "rejected";
    }

    if (normalized.includes("PEND")) {
      return "pending";
    }

    return "unknown";
  }

  private static extractTransactionIdFromCsvRow(
    row: TesabizWithdrawCsvRow
  ): string | null {
    const rawId = row.transactionId ?? row.transaction_id ?? row.id;
    const trimmed = rawId ? rawId.toString().trim() : "";
    return trimmed.length > 0 ? trimmed : null;
  }

  static async reconcileWithdrawalsFromCsv(params: {
    fileBuffer: Buffer;
  }): Promise<{ success: true; message: string; result: ReconciliationResult }> {
    const { fileBuffer } = params;

    const rows = await parseCsvFile<TesabizWithdrawCsvRow>(
      fileBuffer,
      ["transactionId", "transaction_id", "id"],
      { normalizeHeaders: true }
    );

    const transactionIds = Array.from(
      new Set(
        rows
          .map((row) => this.extractTransactionIdFromCsvRow(row))
          .filter((id): id is string => Boolean(id))
      )
    );

    if (transactionIds.length === 0) {
      const err: any = new Error(
        "No se encontraron IDs válidos en el CSV. Usa columna transactionId (o transaction_id/id)."
      );
      err.code = "CSV_EMPTY";
      throw err;
    }

    if (transactionIds.length > TESABIZ_WITHDRAW_RECONCILIATION_MAX_ROWS) {
      const err: any = new Error(
        `Solo se permiten ${TESABIZ_WITHDRAW_RECONCILIATION_MAX_ROWS} transacciones por ejecución.`
      );
      err.code = "CSV_LIMIT_EXCEEDED";
      throw err;
    }

    const { default: WithdrawsService } = await import("./withdraws");
    const { default: TransactionsService } = await import("./transactions");
    const { default: SQSProducer } = await import("./sqs-producer");

    const result: ReconciliationResult = {
      totalRows: transactionIds.length,
      completedInMeru: 0,
      pendingInMeru: 0,
      rejectedAndRefundQueuedInMeru: 0,
      skippedNotFound: 0,
      skippedNotWithdrawal: 0,
      skippedNotTesabizWithdrawal: 0,
      failed: 0,
      details: [],
    };

    for (const transactionId of transactionIds) {
      try {
        const transaction = await prisma.transaction.findUnique({
          where: { id: transactionId },
          include: { boQrCodePayment: true },
        });

        if (!transaction) {
          result.skippedNotFound += 1;
          result.details.push({ transactionId, action: "skipped_not_found" });
          continue;
        }

        if (transaction.type !== TransactionType.WITHDRAWAL) {
          result.skippedNotWithdrawal += 1;
          result.details.push({
            transactionId,
            action: "skipped_not_withdrawal",
          });
          continue;
        }

        if (
          transaction.paymentMethod !== PaymentMethod.BO_QR_CODE ||
          !transaction.boQrCodePayment?.tesabizQrCodeId
        ) {
          result.skippedNotTesabizWithdrawal += 1;
          result.details.push({
            transactionId,
            action: "skipped_not_tesabiz_qr_withdrawal",
          });
          continue;
        }

        const tesabizResponse =
          await TesabizService.getPaymentDetailsByTransactionId({
            transactionId,
            qrCodePaymentId: transaction.boQrCodePayment.tesabizQrCodeId,
          });

        const tesabizStatus = tesabizResponse?.infoTx?.estadoTx ?? "";
        const normalizedStatus = this.normalizeTesabizWithdrawStatus(tesabizStatus);
        const targetMeruStatus =
          normalizedStatus === "completed"
            ? TransactionStatus.COMPLETED
            : normalizedStatus === "pending"
              ? TransactionStatus.PENDING
              : normalizedStatus === "rejected"
                ? TransactionStatus.REJECTED
                : null;

        if (normalizedStatus === "unknown") {
          result.details.push({
            transactionId,
            action: "skipped_unmapped_tesabiz_status_no_change",
            tesabizStatus,
          });
          continue;
        }

        // Idempotent reconciliation: if already aligned with Tesabiz state, do nothing.
        if (targetMeruStatus && transaction.status === targetMeruStatus) {
          result.details.push({
            transactionId,
            action: "already_aligned_no_change",
            tesabizStatus,
          });
          continue;
        }

        if (normalizedStatus === "completed") {
          await WithdrawsService.confirmFiatWithdraw(
            transactionId,
            "completed",
            null,
            null,
            true
          );
          result.completedInMeru += 1;
          result.details.push({
            transactionId,
            action: "completed_in_meru",
            tesabizStatus,
          });
          continue;
        }

        if (normalizedStatus === "pending") {
          await TransactionsService.updateTransactionStatus(
            transactionId,
            TransactionStatus.PENDING
          );
          result.pendingInMeru += 1;
          result.details.push({
            transactionId,
            action: "pending_in_meru",
            tesabizStatus,
          });
          continue;
        }

        await WithdrawsService.confirmFiatWithdraw(
          transactionId,
          "FAILED",
          null,
          "Cancelada en Tesabiz",
          true
        );

        await SQSProducer.produce(SQS.TRANSACTIONS.REFUND, {
          MessageAttributes: {
            Title: { DataType: "String", StringValue: "The Whistler" },
          },
          MessageBody: {
            topic: SQS.TRANSACTIONS.REFUND,
            body: { transactionId, isReprocess: true },
          },
          MessageDeduplicationId: transactionId,
        });

        result.rejectedAndRefundQueuedInMeru += 1;
        result.details.push({
          transactionId,
          action: "rejected_and_refund_queued_in_meru",
          tesabizStatus,
        });
      } catch (error: any) {
        logger.error(
          `[Tesabiz Withdraw Reconciliation] Error processing transaction ${transactionId}: ${error?.message || error}`
        );
        result.failed += 1;
        result.details.push({
          transactionId,
          action: "failed",
          reason: error?.message || "Unknown error",
        });
      }
    }

    return {
      success: true,
      message: "Conciliación de retiros Tesabiz finalizada.",
      result,
    };
  }
}

export default TesabizService;
